# Generated by Django 2.2.6 on 2019-11-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('available_timing', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('ordered_items', models.CharField(max_length=100)),
                ('bill_amount', models.IntegerField()),
                ('order_timestamp', models.DateTimeField()),
                ('food', models.ManyToManyField(to='restaurant.FoodDetail')),
            ],
        ),
    ]
