# Generated by Django 2.2.6 on 2019-11-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_orderdetail_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='ordered_items',
            field=models.CharField(max_length=255),
        ),
    ]
